[package]
name = "rustls-example"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
viz = { workspace = true, features = ["rustls"] }

tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
